file:

  inputPaths:
  #    - "/Users/felipeseho/Desktop/bases/fastshop_rollover_2026-04-29.csv"
  #  - "/Users/felipeseho/Desktop/bases/ligga_rollover_2026-04-29.csv"
      - "/Users/felipeseho/Desktop/bases/unifique_rollover_2026-04-29.csv"
  #    - "/Users/felipeseho/Desktop/bases/seho_test.csv"

  batchLines: 200
  startLine: 1
  # maxLines: 1 # Opcional: limita o número de linhas a processar (útil para testes)
  csvDelimiter: ","

  log:
    path: "logs" # Diretório onde os logs serão salvos
    level: "DEBUG" # Nível de log (DEBUG, INFO, WARNING, ERROR)

  checkpoint:
    path: "checkpoints" # Diretório onde os checkpoints serão salvos

  columns:
    - column: "subscription_id"
      type: "string"
    - column: "campaign"
      type: "string"
    - column: "user_cpf"
      type: "string"
    - column: "user_cnpj"
      type: "string"
    - column: "user_email"
      type: "string"
    - column: "user_msisdn"
      type: "string"
    - column: "status"
      type: "string"
    - column: "partner"
      type: "string"
    - column: "subpartner_id"
      type: "string"
    - column: "event_date"
      type: "date"
      format: "yyyy-MM-dd'T'HH:mm:ss"

api:

  defaultEndpoint: "subscription_create" # Endpoint padrão caso não haja roteamento ou coluna de endpoint

  routing:
    column: "status"
    map:
      "I": "subscription_create"
      "C": "subscription_delete"

  endpoints:
    - name: "subscription_create"

      endpointUrl: "https://api-corporativo.whitelabel.com.br/hub/v1/b2b/{partner}/v2/subscription"
      # endpointUrl: "https://test-seho.requestcatcher.com/hub-connect/v2/hub-connect-api/{partner}/v2/subscription"

      # headers:
      #   Authorization: "Bearer seu-token-aqui"
      #   X-Custom-Header: "valor-customizado"
      method: "POST"
      requestTimeout: 30
      retryAttempts: 3
      retryDelaySeconds: 5
      maxRequestsPerSecond: 100
      mapping:
        - attribute: "subscription_id"
          csvColumn: "subscription_id"
        - attribute: "campaign"
          csvColumn: "campaign"
        - attribute: "user.cpf"
          csvColumn: "user_cpf"
          transform: "empty-to-null"
        - attribute: "user.cnpj"
          csvColumn: "user_cnpj"
          transform: "empty-to-null"
        - attribute: "user.email"
          csvColumn: "user_email"
          transform: "empty-to-null"
        - attribute: "user.msisdn"
          csvColumn: "user_msisdn"
          transform: "empty-to-null"
        - attribute: "partner"
          csvColumn: "partner"
          transform: "empty-to-null"
        - attribute: "subpartner_id"
          csvColumn: "subpartner_id"
          transform: "empty-to-null"
        - attribute: "subscriptionStartDate"
          csvColumn: "event_date"

    - name: "subscription_delete"

      endpointUrl: "https://api-corporativo.whitelabel.com.br/hub/v1/b2b/{partner}/v2/subscription/{subscription_id}/{campaign}"
      #endpointUrl: "https://test-seho.requestcatcher.com/hub-connect/v2/hub-connect-api/partner/{partner}/v2/subscription/{subscription_id}/{campaign}"

      # headers:
      #   Authorization: "Bearer seu-token-aqui"
      #   X-Custom-Header: "valor-customizado"
      method: "DELETE"
      requestTimeout: 30
      retryAttempts: 3
      retryDelaySeconds: 5
      maxRequestsPerSecond: 100
      mapping:
        - attribute: "subscriptionEndDate"
          csvColumn: "event_date"